# Usar PHP 8.3 FPM como base
FROM php:8.3-fpm

# Instalar dependências do sistema para PHP, Node.js e Composer
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    unzip \
    git \
    curl \
    libonig-dev \
    libxml2-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql mbstring xml \
    && curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs

# Instalar Composer (PHP)
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Definir diretório de trabalho
WORKDIR /var/www/html

# Copiar os arquivos de dependência do PHP e Node.js
COPY composer.json composer.lock ./
COPY package.json package-lock.json ./

# Copiar o restante do código da aplicação Laravel
COPY . .

# Alterar permissões dos arquivos
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 /var/www/html

# Instalar dependências do Laravel (PHP)
RUN composer install --no-interaction --prefer-dist

# Instalar dependências do Node.js (incluindo Vite)
RUN npm install

# Expor as portas necessárias
EXPOSE 9000
EXPOSE 5173 
EXPOSE 80

# Comando para rodar PHP-FPM e Vite no terminal
CMD php-fpm
